# Generated by Django 3.2.12 on 2022-02-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('fi_branch_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='FI Branch ID')),
                ('branch_nm', models.CharField(max_length=255, verbose_name='Branch Name')),
            ],
            options={
                'db_table': 'd_fi_branch',
            },
        ),
        migrations.CreateModel(
            name='FinancialInstituteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='financial institute type')),
            ],
            options={
                'db_table': 'd_fi_type',
            },
        ),
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('geo_area_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Geo Area ID')),
                ('country_id', models.IntegerField(verbose_name='Country ID')),
                ('division', models.CharField(max_length=255, verbose_name='Division')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
                ('thana_upazilla', models.CharField(max_length=255, verbose_name='Upazila')),
            ],
            options={
                'db_table': 'd_geo_area',
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitute',
            fields=[
                ('fi_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='FI ID')),
                ('fi_nm', models.CharField(max_length=255, verbose_name='financial institute')),
                ('fi_alias', models.CharField(max_length=255, verbose_name='alias')),
                ('fi_class_id', models.IntegerField(verbose_name='FI Class ID')),
                ('fi_status', models.IntegerField(verbose_name='FI Status')),
                ('financial_institute_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitutetype')),
                ('geo_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.geoarea')),
            ],
            options={
                'db_table': 'd_fi',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.branch')),
                ('financial_institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitute')),
                ('financial_institute_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitutetype')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='fi_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitute'),
        ),
        migrations.AddField(
            model_name='branch',
            name='geo_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutes.geoarea'),
        ),
    ]
