# Generated by Django 3.2.12 on 2022-02-24 07:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ereturns.common.file_upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitCoaValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa', models.IntegerField(blank=True, null=True, verbose_name='Chart of Account')),
            ],
            options={
                'db_table': 'rit_validation_coa',
            },
        ),
        migrations.CreateModel(
            name='RitCurrencyValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(blank=True, null=True, verbose_name='Currency')),
            ],
            options={
                'db_table': 'rit_validation_currency',
            },
        ),
        migrations.CreateModel(
            name='RitFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('frequency', models.IntegerField(choices=[(1, 'Daily'), (2, 'Weekly'), (3, 'Monthly'), (4, 'Quarterly'), (5, 'Semi Annual'), (6, 'Yearly')], default=1)),
                ('version', models.FloatField(blank=True, verbose_name='version')),
                ('column', models.IntegerField(verbose_name='column(s)')),
                ('row', models.IntegerField(verbose_name='row(s)')),
                ('cut_off_days', models.IntegerField(verbose_name='cut off day(s)')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0)),
                ('validate', models.BooleanField(default=False, verbose_name='validate')),
            ],
            options={
                'db_table': 'rit_features',
            },
        ),
        migrations.CreateModel(
            name='RitManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, 'RIT'), (2, 'Reference File'), (3, 'User Manual'), (4, 'User Registration Form')], default=1)),
                ('file', models.FileField(upload_to=ereturns.common.file_upload.rit_directory_path)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='version')),
            ],
            options={
                'db_table': 'rit_management',
            },
        ),
        migrations.CreateModel(
            name='RitSupervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='department')),
                ('base_date', models.DateTimeField(verbose_name='base date')),
                ('file', models.FileField(upload_to=ereturns.common.file_upload.directory_path)),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('prepared_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='prepared by')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time')),
                ('status', models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Failed to upload for error at first row')], default=1)),
                ('ip', models.CharField(blank=True, max_length=255, verbose_name='ip address')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.branch')),
                ('financial_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitute')),
                ('financial_institute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.financialinstitutetype')),
                ('rit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_supervision',
            },
        ),
    ]
