# Generated by Django 3.2.12 on 2022-03-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DDates',
            fields=[
                ('date_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cal_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StgTMeDFrxEchPos',
            fields=[
                ('date_id', models.FloatField(primary_key=True, serialize=False)),
                ('ccy_id', models.FloatField()),
                ('fi_id', models.FloatField()),
                ('monetary_coa_id', models.FloatField()),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('amount_fcy', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('user_code', models.IntegerField(blank=True, null=True)),
                ('load_date', models.DateField(blank=True, null=True)),
                ('identity_code', models.IntegerField(blank=True, null=True)),
                ('valid_ind', models.BooleanField()),
                ('ref_err', models.CharField(blank=True, max_length=200, null=True)),
                ('open_position_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'stg_t_me_d_frx_ech_pos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitRefCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Ref Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_ref_code',
            },
        ),
    ]
