# Generated by Django 3.2.12 on 2022-03-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0003_ddates_ritrefcodevalidation_stgtmedfrxechpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTMeDFrxEchPos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=25, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('me_coa', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.CharField(blank=True, max_length=25, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=25, null=True)),
                ('open_position_limit', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_d_frx_ech_pos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMAssFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=25, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=25, null=True)),
                ('monetary_coa_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ass_for',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMAssForObu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=25, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=25, null=True)),
                ('monetary_coa_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ass_for_obu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMAssLiab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('me_coa', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ass_liab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMAssLiabObu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('me_coa', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ass_liab_obu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMAssLiabSuppSbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('monetary_coa_id', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ass_liab_supp_sbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMEbankingEcommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coa_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_in_number', models.CharField(blank=True, max_length=255, null=True)),
                ('data_in_text', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_ebanking_ecommerce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMFrcTrn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payrec_purpose_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=255, null=True)),
                ('importer_exporter', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('encashment_no_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_fcy', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_count', models.CharField(blank=True, max_length=255, null=True)),
                ('encashment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sched_code', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_frc_trn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMLnaDl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_purpose_id', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_outstanding_amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_actual_amount_disbursed', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_interest_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_recovered_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('written_off_amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_lna_dl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMLnaDlObu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_purpose_id', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_outstanding_amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_actual_amount_disbursed', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_interest_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('cur_recovered_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('written_off_amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_lna_dl_obu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMPortInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_position_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('gain_loss', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_position', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('security_code', models.CharField(blank=True, max_length=255, null=True)),
                ('economic_sector', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_port_inv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMPortSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nita_coa', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_port_survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeQInvNonResFi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('investor_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enterprise_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_major_activities', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('mecoa_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_position_date', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_increase', models.CharField(blank=True, max_length=255, null=True)),
                ('position_decrease', models.CharField(blank=True, max_length=255, null=True)),
                ('changes_due_to_exchange_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('changes_due_to_price_change', models.CharField(blank=True, max_length=255, null=True)),
                ('change_due_to_others', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_position_reported', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_position_calculated', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_q_inv_non_res_fi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsDLoanSpResSt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=20, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=25, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=25, null=True)),
                ('application_no', models.CharField(blank=True, max_length=25, null=True)),
                ('application_approved', models.CharField(blank=True, max_length=25, null=True)),
                ('outstanding_amount', models.CharField(blank=True, max_length=25, null=True)),
                ('down_payment_amount', models.CharField(blank=True, max_length=25, null=True)),
                ('interest_suspense', models.CharField(blank=True, max_length=25, null=True)),
                ('unapplied_interest', models.CharField(blank=True, max_length=25, null=True)),
                ('interest_waived', models.CharField(blank=True, max_length=25, null=True)),
                ('amount_rescheduled_exit', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_d_loan_sp_res_st',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitCommodityValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.IntegerField(blank=True, null=True, verbose_name='Commodity')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_commodity',
            },
        ),
        migrations.CreateModel(
            name='RitCompanyValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.IntegerField(blank=True, null=True, verbose_name='Company')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_company',
            },
        ),
        migrations.CreateModel(
            name='RitCountryValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(blank=True, null=True, verbose_name='Country ID')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_country',
            },
        ),
        migrations.CreateModel(
            name='RitEcoPurposeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.IntegerField(blank=True, null=True, verbose_name='Eco Purpose')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_eco_purpose',
            },
        ),
        migrations.CreateModel(
            name='RitEcoSectorValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.IntegerField(blank=True, null=True, verbose_name='Eco Sector')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_eco_sector',
            },
        ),
        migrations.CreateModel(
            name='RitEnterpriseTypeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_type', models.IntegerField(blank=True, null=True, verbose_name='Enterprise Type')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_enterprise_type',
            },
        ),
        migrations.CreateModel(
            name='RitInstrumentTypeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.IntegerField(blank=True, null=True, verbose_name='Instrument Type')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_instrument_type',
            },
        ),
        migrations.CreateModel(
            name='RitInvestorChannelValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_channel', models.IntegerField(blank=True, null=True, verbose_name='Investor Channel')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_investor_channel',
            },
        ),
        migrations.CreateModel(
            name='RitInvestorValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.IntegerField(blank=True, null=True, verbose_name='Investor ID')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_investor',
            },
        ),
        migrations.CreateModel(
            name='RitPayrecPurposeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payrec_purpose', models.IntegerField(blank=True, null=True, verbose_name='Pay Rec Purpose')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_payrec_purpose',
            },
        ),
        migrations.CreateModel(
            name='RitProductCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(blank=True, null=True, verbose_name='Product Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_product_code',
            },
        ),
        migrations.CreateModel(
            name='RitProductTypeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(blank=True, null=True, verbose_name='Product Type')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_product_type',
            },
        ),
        migrations.CreateModel(
            name='RitRepTypeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_type', models.IntegerField(blank=True, null=True, verbose_name='Unit of Measure')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_rep_type',
            },
        ),
        migrations.CreateModel(
            name='RitScheduledCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_code', models.IntegerField(blank=True, null=True, verbose_name='Scheduled Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_scheduled_code',
            },
        ),
        migrations.CreateModel(
            name='RitSectorMajorActivitiesValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_major_activities', models.IntegerField(blank=True, null=True, verbose_name='Sector Major Activities')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_sector_major_activities',
            },
        ),
        migrations.CreateModel(
            name='RitSecurityCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.IntegerField(blank=True, null=True, verbose_name='Investor ID')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_security_code',
            },
        ),
        migrations.CreateModel(
            name='RitTypeCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.IntegerField(blank=True, null=True, verbose_name='Type Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_type_code',
            },
        ),
        migrations.CreateModel(
            name='RitUnitOfMeasureValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.IntegerField(blank=True, null=True, verbose_name='Unit of Measure')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_unit_of_measure',
            },
        ),
        migrations.DeleteModel(
            name='StgTMeDFrxEchPos',
        ),
    ]
