# Generated by Django 3.2.12 on 2022-03-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0004_auto_20220321_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTMeDRemittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sched_code', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payrec_purpose_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(blank=True, max_length=255, null=True)),
                ('district_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nid', models.CharField(blank=True, max_length=255, null=True)),
                ('passport', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_fcy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_d_remittance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMDepoDri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_depo_dri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMFrcTrnSupp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rep_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sched_code', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ccy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(blank=True, max_length=255, null=True)),
                ('encashment_no_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('encashment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('importer_exporter', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_fcy', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_frc_trn_supp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeMLnaRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('advances_bdt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_lna_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeQInvForFi1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.FloatField(blank=True, null=True)),
                ('fi_name', models.FloatField(blank=True, null=True)),
                ('investor_channel', models.FloatField(blank=True, null=True)),
                ('company_name', models.FloatField(blank=True, null=True)),
                ('legal_enterprise', models.FloatField(blank=True, null=True)),
                ('enterprise_type', models.FloatField(blank=True, null=True)),
                ('enterprise_location', models.FloatField(blank=True, null=True)),
                ('sector_major_activities', models.FloatField(blank=True, null=True)),
                ('date_incorporation_reg', models.DateField(blank=True, null=True)),
                ('date_of_imp', models.DateField(blank=True, null=True)),
                ('fellow_enterprise', models.FloatField(blank=True, null=True)),
                ('location_fellow_ent', models.FloatField(blank=True, null=True)),
                ('location_common_parent', models.FloatField(blank=True, null=True)),
                ('investor_name', models.FloatField(blank=True, null=True)),
                ('country', models.FloatField(blank=True, null=True)),
                ('percentage_equity_share', models.FloatField(blank=True, null=True)),
                ('total_foreign_inv_bdt', models.FloatField(blank=True, null=True)),
                ('total_external_debt', models.FloatField(blank=True, null=True)),
                ('total_paid_up', models.FloatField(blank=True, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('imported_by', models.FloatField(blank=True, null=True)),
                ('imp_amount', models.FloatField(blank=True, null=True)),
                ('capital_contribution', models.FloatField(blank=True, null=True)),
                ('number_foreign_employee', models.FloatField(blank=True, null=True)),
                ('num_local_employee', models.FloatField(blank=True, null=True)),
                ('other_bank', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_q_inv_for_fi_1',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ritreptypevalidation',
            name='rep_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Report Type'),
        ),
        migrations.CreateModel(
            name='RitLegalFormOfEnterpriseValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_form_of_enterprise', models.IntegerField(blank=True, null=True, verbose_name='Legal Form Of Enterprise')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_legal_form_of_enterprise',
            },
        ),
        migrations.CreateModel(
            name='RitFellowEnterpriseLocationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellow_enterprise_location', models.IntegerField(blank=True, null=True, verbose_name='Fellow Enterprise Location')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_fellow_enterprise_location',
            },
        ),
        migrations.CreateModel(
            name='RitEnterpriseLocationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_location', models.IntegerField(blank=True, null=True, verbose_name='Enterprise Location')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_enterprise_location',
            },
        ),
        migrations.CreateModel(
            name='RitCommonParentLocationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_parent_location', models.IntegerField(blank=True, null=True, verbose_name='Common Parent Location')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_common_parent_location',
            },
        ),
    ]
