# Generated by Django 3.2.12 on 2022-03-28 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0005_auto_20220323_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTMeQInvForFi2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('investor_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_major_activities', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_enterprise', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_imp', models.CharField(blank=True, max_length=255, null=True)),
                ('location_ent', models.CharField(blank=True, max_length=255, null=True)),
                ('total_paid_up', models.CharField(blank=True, max_length=255, null=True)),
                ('name_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('country_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage_equity_shareinvst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('legal_form_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_major_activities_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_imp_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('total_equity_invst_abroad_amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('total_paid_up_invst_ent_abroad', models.CharField(blank=True, max_length=255, null=True)),
                ('fellow_enterprise', models.CharField(blank=True, max_length=255, null=True)),
                ('location_fellow_enterprise', models.CharField(blank=True, max_length=255, null=True)),
                ('location_common_parent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_q_inv_for_fi_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitLoadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fi', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField(blank=True, default=0, max_length=255, null=True)),
                ('load_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'db_table': 'rit_load_status',
            },
        ),
    ]
