# Generated by Django 3.2.12 on 2022-03-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0006_exttmeqinvforfi2_ritloadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTMeMSted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('debtor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('instrument_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('tradable_item', models.CharField(blank=True, max_length=255, null=True)),
                ('creditor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('creditor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('country_id', models.CharField(blank=True, max_length=255, null=True)),
                ('all_cost_percent_annum', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_borrowing_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('f_drawing_disb_date', models.CharField(blank=True, max_length=255, null=True)),
                ('l_principal_pay_date', models.CharField(blank=True, max_length=255, null=True)),
                ('maturity_in_days', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_pos_principal_outs', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_drawn_during_rep_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_paid_dur_rep_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_paid_dur_rep_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('others_fees_rep_mon', models.CharField(blank=True, max_length=255, null=True)),
                ('overdue_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_position', models.CharField(blank=True, max_length=255, null=True)),
                ('lc_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_m_sted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTMeQAcep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('economic_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sanction_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursement_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('classified_amount_ss', models.CharField(blank=True, max_length=255, null=True)),
                ('classified_amount_df', models.CharField(blank=True, max_length=255, null=True)),
                ('classified_amount_b_l', models.CharField(blank=True, max_length=255, null=True)),
                ('unclassified_amount_sma', models.CharField(blank=True, max_length=255, null=True)),
                ('unclassified_amount_std', models.CharField(blank=True, max_length=255, null=True)),
                ('overdue_amount', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_q_acep',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ritloadstatus',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='RitInstrumentClassificationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_classification', models.IntegerField(blank=True, null=True, verbose_name='Instrument Classification')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_instrument_classification',
            },
        ),
        migrations.CreateModel(
            name='RitCreditorTypeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_type', models.IntegerField(blank=True, null=True, verbose_name='Creditor Type')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_creditor_type',
            },
        ),
    ]
