# Generated by Django 3.2.12 on 2022-03-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0007_auto_20220331_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTMeQSmeLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sme_category', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('ln_segregation', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_enterprise', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_enterprise', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursement', models.CharField(blank=True, max_length=255, null=True)),
                ('outstanding', models.CharField(blank=True, max_length=255, null=True)),
                ('ln_recovery', models.CharField(blank=True, max_length=255, null=True)),
                ('classified', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_others', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_me_q_sme_loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitSmeSubCategoryValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sme_sub_category', models.IntegerField(blank=True, null=True, verbose_name='SME Sub Category')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_sme_sub_category',
            },
        ),
        migrations.CreateModel(
            name='RitSmeCategoryValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sme_category', models.IntegerField(blank=True, null=True, verbose_name='SME Category')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_sme_category',
            },
        ),
        migrations.CreateModel(
            name='RitLoanSegregationValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_segregation', models.IntegerField(blank=True, null=True, verbose_name='Loan Segregation')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_loan_segregation',
            },
        ),
    ]
