# Generated by Django 3.2.12 on 2022-04-10 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0009_exttmeqlnav2_ritaccountnumbervalidation_ritcollateralidvalidation_ritgendercodevalidation_ritindustr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTPsDAsliBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_coa', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_credit_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_usd', models.CharField(blank=True, max_length=255, null=True)),
                ('banking_class', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_d_asli_balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitFrequencyIndicatorCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_ind_code', models.IntegerField(blank=True, null=True, verbose_name='Frequency Indicator Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_frequency_indicator_code',
            },
        ),
        migrations.CreateModel(
            name='RitDebitCardIndicatorCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_ind_code', models.IntegerField(blank=True, null=True, verbose_name='Debit Card Indicator Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_debit_card_indicator_code',
            },
        ),
        migrations.CreateModel(
            name='RitBankingClassValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banking_class', models.IntegerField(blank=True, null=True, verbose_name='Banking Class')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_banking_class',
            },
        ),
    ]
