# Generated by Django 3.2.12 on 2022-04-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0010_exttpsdaslibalances_ritbankingclassvalidation_ritdebitcardindicatorcodevalidation_ritfrequencyindica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTPsMInterSa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aging_range_id', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_accounts', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_m_inter_sa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsMInterTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orig_fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unrecon_start', models.CharField(blank=True, max_length=255, null=True)),
                ('unrecon_end', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_credit_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('aging_range_id', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_count', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('advice_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_m_inter_trx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitAgingRangeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aging_range_id', models.IntegerField(blank=True, null=True, verbose_name='Aging Range')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_aging_range_id',
            },
        ),
        migrations.CreateModel(
            name='RitAccountTypeCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_code', models.IntegerField(blank=True, null=True, verbose_name='Account Type')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_account_type_code',
            },
        ),
    ]
