# Generated by Django 3.2.12 on 2022-04-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0011_exttpsmintersa_exttpsmintertrx_ritaccounttypecodevalidation_ritagingrangevalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTPsMDpstSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_area_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_m_dpst_sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsMIntRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('eco_sector_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('highest_interest_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('lowest_interest_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_classification', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_m_int_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsMIntWaiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('waiver_amt_charge_debit_ac', models.CharField(blank=True, max_length=255, null=True)),
                ('waiver_amt_charge_debit_int_su', models.CharField(blank=True, max_length=255, null=True)),
                ('uncharged', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_loan_accounts', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_m_int_waiver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitReportingAreaValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_area', models.IntegerField(blank=True, null=True, verbose_name='Reporting Area')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_reporting_area',
            },
        ),
    ]
