# Generated by Django 3.2.12 on 2022-04-13 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rit', '0012_exttpsmdpstsector_exttpsmintrate_exttpsmintwaiver_ritreportingareavalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTPsDLnProv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_class_id', models.CharField(blank=True, max_length=255, null=True)),
                ('aging_range_id', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_ind_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amt_provision_reqd', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_suspense', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_provision', models.CharField(blank=True, max_length=255, null=True)),
                ('base_for_provision', models.CharField(blank=True, max_length=255, null=True)),
                ('outstanding_amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('insterest_suspense_against_sma', models.CharField(blank=True, max_length=255, null=True)),
                ('value_of_eligible_securities', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_d_ln_prov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsDSlrCashRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_coa', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_date', models.CharField(blank=True, max_length=255, null=True)),
                ('min_liquid_assets_reqd', models.CharField(blank=True, max_length=255, null=True)),
                ('surplus_deficit', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_d_slr_cash_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtTPsQLawsSuits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.CharField(blank=True, max_length=255, null=True)),
                ('fi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lawsuit_type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('case_type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_period', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('suit_count', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_t_ps_q_laws_suits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RitLawSuitTypeCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawsuit_type_code', models.IntegerField(blank=True, null=True, verbose_name='Law Suit Type Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_lawsuit_type_code',
            },
        ),
        migrations.CreateModel(
            name='RitCaseTypeCodeValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type_code', models.IntegerField(blank=True, null=True, verbose_name='Case Type Code')),
                ('rit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rit.ritfeatures')),
            ],
            options={
                'db_table': 'rit_validation_case_type_code',
            },
        ),
    ]
